"Updated flutter version and changed ping target to 1.1.1.1, replaced wget with curl for chromedriver download"

diff --git a/.github/workflows/flutter_ci_cd.yaml b/.github/workflows/flutter_ci_cd.yaml
--- a/.github/workflows/flutter_ci_cd.yaml
+++ b/.github/workflows/flutter_ci_cd.yaml
@@ -61,18 +61,18 @@ jobs:
       uses: subosito/flutter-action@v2
       with:
         flutter-version: 3.24.0
-
     - name: Check Internet Connection
       run: |
-        ping -c 3 google.com || (echo "Internet connection issue, aborting" && exit 1)
-
+        ping -c 3 1.1.1.1 || (echo "Internet connection issue, aborting" && exit 1)
+      
     - name: Install ChromeDriver
       run: |
         CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
         CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
-        wget -N https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
+        curl -o chromedriver_linux64.zip https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
         unzip chromedriver_linux64.zip -d /usr/local/bin/
         chmod +x /usr/local/bin/chromedriver
+      
 
     - name: Start ChromeDriver
       run: |
